
# services:
#   node-app-dev:
#     build: .
#     env_file:
#       - .env.dev
#     expose:
#       - 3000
#     command: node server.js --port 3000

#   node-app-prod:
#     build: .
#     env_file:
#       - .env.prod
#     expose:
#       - 3001
#     command: node server.js --port 3001
services:
  node-app-dev:
    build: .
    environment:
      - BG_COLOR=${DEV_BG_COLOR}
      - PORT=${DEV_PORT}
    expose:
      - ${DEV_PORT}
    command: node server.js --port ${DEV_PORT}

  node-app-prod:
    build: .
    environment:
      - BG_COLOR=${PROD_BG_COLOR}
      - PORT=${PROD_PORT}
    expose:
      - ${PROD_PORT}
    command: node server.js --port ${PROD_PORT}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node-app-dev
      - node-app-prod



# version: '3.8'
# services:
#   node_dev:
#     build: .
#     environment:
#       - BG_COLOR=purple   # змінюй на потрібний колір для dev
#     expose:
#       - 3000

#   node_prod:
#     build: .
#     environment:
#       - BG_COLOR=green    # змінюй на потрібний колір для prod
#     expose:
#       - 3000

#   nginx:
#     image: nginx:alpine
#     depends_on:
#       - node_dev
#       - node_prod
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./certbot/conf:/etc/letsencrypt
#     ports:
#       - "80:80"
#       - "443:443"
