# version: '3.8'
# services:
#   node-app:
#     build: .
#     environment:
#       - BG_COLOR=${BG_COLOR}
#     expose:
#       - 3000

#   nginx:
#     image: nginx:alpine
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./html_dev:/usr/share/nginx/html_dev
#       - ./html_prod:/usr/share/nginx/html_prod
#       - ./certbot/conf:/etc/letsencrypt
#     ports:
#       - "80:80"
#       - "443:443"

#   certbot:
#     image: certbot/certbot
#     volumes:
#       - ./certbot/conf:/etc/letsencrypt
#       - ./html_dev:/usr/share/nginx/html_dev
#       - ./html_prod:/usr/share/nginx/html_prod

version: '3.8'
services:
  node-app:
    build: .
    environment:
      - BG_COLOR=${BG_COLOR}
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}

