name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to dev using Ansible
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/devops-test
            git fetch origin
            git checkout dev
            git pull origin dev
            ansible-playbook -i inventory.ini playbook.yml \
              --extra-vars "bg_color=green domain=dev.iatnih.pp.ua email=${{ secrets.SSL_EMAIL }}"
